### ISSUE TITLE
i Want to export two Tables

### ISSUE THREAD

**Issue by HandSomeWeiWei** [HandSomeWeiWei/ShoppingWeb#2]
I have generated a Checkbox in my table using.

<th data-sortable="true" data-checkbox="true" data-field="checkboxSelect" data-formatter="checkedFormatter">

I would like to instantly sort or send the row I selected Up to the top of the table. Is there a way to do this?
The reason for this, is when working with large datasets, it is difficult to scroll down to see all of the rows you have selected. Sending them to the top of the table would make it so that they could review their selections before finalizing any changes.

**Comment by HandSomeWeiWei** [comment]
祖瀚解決

**Comment by JiangZuHan** [comment]
NO

**Comment by HandSomeWeiWei** [comment]
解決正確
